"""Connector contracts and registry helpers."""

from .models import (
    CONNECTOR_ACTION_CONTRACT_VERSION,
    ConnectorAction,
    ConnectorActionRequest,
    ConnectorActionOutcome,
    ConnectorActionResult,
    ConnectorArtifactDomain,
    ConnectorCapabilities,
    ConnectorConfigField,
    ConnectorConfigSummary,
    ConnectorDefinition,
    ConnectorExecutionAction,
    ConnectorFailureMode,
    ConnectorGuardrails,
    ConnectorRegistryEntry,
    ConnectorSystemKind,
    ConnectorTransportPattern,
    ConnectorValidationIssue,
)
from .registry import (
    configure_connector_entry,
    get_connector_definition,
    get_connector_registry_entry,
    list_connector_definitions,
    list_connector_registry_entries,
    summarize_connector_config,
    validate_connector_config,
    validate_connector_entry,
)
from .runtime import execute_connector_action

__all__ = [
    "CONNECTOR_ACTION_CONTRACT_VERSION",
    "ConnectorAction",
    "ConnectorActionRequest",
    "ConnectorActionOutcome",
    "ConnectorActionResult",
    "ConnectorArtifactDomain",
    "ConnectorCapabilities",
    "ConnectorConfigField",
    "ConnectorConfigSummary",
    "ConnectorDefinition",
    "ConnectorExecutionAction",
    "ConnectorFailureMode",
    "ConnectorGuardrails",
    "ConnectorRegistryEntry",
    "ConnectorSystemKind",
    "ConnectorTransportPattern",
    "ConnectorValidationIssue",
    "configure_connector_entry",
    "get_connector_definition",
    "get_connector_registry_entry",
    "list_connector_definitions",
    "list_connector_registry_entries",
    "summarize_connector_config",
    "validate_connector_config",
    "validate_connector_entry",
    "execute_connector_action",
]
